node['ssmtp'] = {}
node['ssmtp']['root_user']
node['ssmtp']['mail_hub']
node['ssmtp']['rewrite_domain']
node['ssmtp']['hostname']
node['ssmtp']['from_line_override']
node['ssmtp']['use_tls']
node['ssmtp']['use_starttls']
node['ssmtp']['tls_cert']
node['ssmtp']['auth_user']
node['ssmtp']['auth_pass']
node['ssmtp']['auth_method']
